-- =====================================================================
-- seed.sql — historical orchestrator (no longer used)
-- =====================================================================
-- Supabase's seed loader does not support psql meta-commands (\ir, \i),
-- so the ordered list of seed files is configured in supabase/config.toml
-- under [db.seed] sql_paths.
--
-- Current ordered run list (see config.toml):
--   1) seeds/01-geography.sql              (provinces, districts, palikas)
--   2) seeds/02-rbac.sql                   (roles only; perms+role_perms in migration 20250127000008)
--   3) seeds/03-categories.sql             (global categories + per-palika business types)
--   4) seeds/04-business-categories.sql    (global business_categories table)
--   5) seeds/05-marketplace-categories.sql (marketplace_categories T1/T2/T3)
--   6) seeds/subscription-tiers.sql        (subscription_tiers, features, tier_features)
--
-- This file is intentionally a no-op to keep historical tooling happy.
-- =====================================================================
SELECT 1;
