-- =====================================================================
-- Geography — provinces, districts, palikas
-- Generated by database/scripts/dump-seeds-to-sql.ts — do not edit by hand.
-- Regenerate by re-running the generator; the file is deleted after commit.
-- =====================================================================

-- Provinces (7) --
INSERT INTO public.provinces (name_en, name_ne, code) VALUES
  ('Koshi Province', 'कोशी प्रदेश', 'P1'),
  ('Madhesh Province', 'मधेश प्रदेश', 'P2'),
  ('Bagmati Province', 'बागमती प्रदेश', 'P3'),
  ('Gandaki Province', 'गण्डकी प्रदेश', 'P4'),
  ('Lumbini Province', 'लुम्बिनी प्रदेश', 'P5'),
  ('Karnali Province', 'कर्णाली प्रदेश', 'P6'),
  ('Sudurpashchim Province', 'सुदूरपश्चिम प्रदेश', 'P7')
ON CONFLICT (code) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne;

-- Districts (77) --
INSERT INTO public.districts (province_id, name_en, name_ne, code)
SELECT p.id, 'Bhojpur', 'भोजपुर', 'D01' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Dhankuta', 'धनकुटा', 'D02' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Ilam', 'इलाम', 'D03' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Jhapa', 'झापा', 'D04' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Khotang', 'खोटाङ', 'D05' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Morang', 'मोरङ', 'D06' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Okhaldhunga', 'ओखलढुङ्गा', 'D07' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Panchthar', 'पञ्चथर', 'D08' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Sankhuwasabha', 'संखुवासभा', 'D09' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Solukhumbu', 'सोलुखुम्बु', 'D10' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Sunsari', 'सुनसरी', 'D11' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Taplejung', 'ताप्लेजुङ', 'D12' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Terhathum', 'तेह्रथुम', 'D13' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Udayapur', 'उदयपुर', 'D14' FROM public.provinces p WHERE p.code = 'P1'
UNION ALL
SELECT p.id, 'Saptari', 'सप्तरी', 'D15' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Siraha', 'सिराहा', 'D16' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Dhanusa', 'धनुषा', 'D17' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Mahottari', 'महोत्तरी', 'D18' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Sarlahi', 'सर्लाही', 'D19' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Bara', 'बारा', 'D20' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Parsa', 'पर्सा', 'D21' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Rautahat', 'रौतहट', 'D22' FROM public.provinces p WHERE p.code = 'P2'
UNION ALL
SELECT p.id, 'Sindhuli', 'सिन्धुली', 'D23' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Ramechhap', 'रामेछाप', 'D24' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Dolakha', 'डोलखा', 'D25' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Bhaktapur', 'भक्तपुर', 'D26' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Dhading', 'धादिङ', 'D27' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Kathmandu', 'काठमाडौं', 'D28' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Kavrepalanchok', 'काभ्रेपलाञ्चोक', 'D29' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Lalitpur', 'ललितपुर', 'D30' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Nuwakot', 'नुवाकोट', 'D31' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Rasuwa', 'रसुवा', 'D32' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Sindhupalchok', 'सिन्धुपाल्चोक', 'D33' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Chitwan', 'चितवन', 'D34' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Makwanpur', 'मकवानपुर', 'D35' FROM public.provinces p WHERE p.code = 'P3'
UNION ALL
SELECT p.id, 'Gorkha', 'गोरखा', 'D36' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Lamjung', 'लमजुङ', 'D37' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Tanahun', 'तनहुँ', 'D38' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Kaski', 'कास्की', 'D39' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Manang', 'मनाङ', 'D40' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Mustang', 'मुस्ताङ', 'D41' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Parbat', 'पर्वत', 'D42' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Syangja', 'स्याङ्जा', 'D43' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Myagdi', 'म्याग्दी', 'D44' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Baglung', 'बागलुङ', 'D45' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Nawalpur', 'नवलपुर', 'D46' FROM public.provinces p WHERE p.code = 'P4'
UNION ALL
SELECT p.id, 'Arghakhanchi', 'अर्घाखाँची', 'D47' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Banke', 'बाँके', 'D48' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Bardiya', 'बर्दिया', 'D49' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Dang', 'दाङ', 'D50' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Gulmi', 'गुल्मी', 'D51' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Kapilvastu', 'कपिलवस्तु', 'D52' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Parasi', 'परासी', 'D53' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Palpa', 'पाल्पा', 'D54' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Pyuthan', 'प्यूठान', 'D55' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Rolpa', 'रोल्पा', 'D56' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Rukum East', 'पूर्वी रुकुम', 'D57' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Rupandehi', 'रुपन्देही', 'D58' FROM public.provinces p WHERE p.code = 'P5'
UNION ALL
SELECT p.id, 'Dolpa', 'डोल्पा', 'D59' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Jumla', 'जुम्ला', 'D60' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Mugu', 'मुगु', 'D61' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Humla', 'हुम्ला', 'D62' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Kalikot', 'कालिकोट', 'D63' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Jajarkot', 'जाजरकोट', 'D64' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Dailekh', 'दैलेख', 'D65' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Salyan', 'सल्यान', 'D66' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Surkhet', 'सुर्खेत', 'D67' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Rukum West', 'पश्चिमी रुकुम', 'D68' FROM public.provinces p WHERE p.code = 'P6'
UNION ALL
SELECT p.id, 'Bajura', 'बाजुरा', 'D69' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Bajhang', 'बझाङ', 'D70' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Doti', 'डोटी', 'D71' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Achham', 'अछाम', 'D72' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Darchula', 'डार्चुला', 'D73' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Baitadi', 'बैतडी', 'D74' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Dadeldhura', 'डडेलधुरा', 'D75' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Kanchanpur', 'कञ्चनपुर', 'D76' FROM public.provinces p WHERE p.code = 'P7'
UNION ALL
SELECT p.id, 'Kailali', 'कैलाली', 'D77' FROM public.provinces p WHERE p.code = 'P7'
ON CONFLICT (code) DO UPDATE SET
  province_id = EXCLUDED.province_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne;

-- Palikas (372) --

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Bhojpur Municipality', 'भोजपुर नगरपालिका', 'municipality', 'D01-M01', 14 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Shadananda Municipality', 'षडानन्द नगरपालिका', 'municipality', 'D01-M02', 10 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Aamchok Rural Municipality', 'आमचोक गाउँपालिका', 'rural_municipality', 'D01-R01', 7 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Arun Rural Municipality', 'अरुण गाउँपालिका', 'rural_municipality', 'D01-R02', 8 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Hatuwagadhi Rural Municipality', 'हतुवागढी गाउँपालिका', 'rural_municipality', 'D01-R03', 9 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Pauwadungma Rural Municipality', 'पौवादुङमा गाउँपालिका', 'rural_municipality', 'D01-R04', 7 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Ramprasad Rai Rural Municipality', 'रामप्रसाद राई गाउँपालिका', 'rural_municipality', 'D01-R05', 6 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Salpasilichho Rural Municipality', 'साल्पासिलिछो गाउँपालिका', 'rural_municipality', 'D01-R06', 6 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Tyamkemaiyung Rural Municipality', 'टेम्केमैयुङ गाउँपालिका', 'rural_municipality', 'D01-R07', 7 FROM public.districts d WHERE d.code = 'D01'
UNION ALL
SELECT d.id, 'Dhankuta Municipality', 'धनकुटा नगरपालिका', 'municipality', 'D02-M01', 10 FROM public.districts d WHERE d.code = 'D02'
UNION ALL
SELECT d.id, 'Mahalaxmi Municipality', 'महालक्ष्मी नगरपालिका', 'municipality', 'D02-M02', 9 FROM public.districts d WHERE d.code = 'D02'
UNION ALL
SELECT d.id, 'Pakhribas Municipality', 'पाख्रीबास नगरपालिका', 'municipality', 'D02-M03', 11 FROM public.districts d WHERE d.code = 'D02'
UNION ALL
SELECT d.id, 'Chaubise Rural Municipality', 'चौविसे गाउँपालिका', 'rural_municipality', 'D02-R01', 9 FROM public.districts d WHERE d.code = 'D02'
UNION ALL
SELECT d.id, 'Chhathar Jorpati Rural Municipality', 'छथर जोरपाटी गाउँपालिका', 'rural_municipality', 'D02-R02', 7 FROM public.districts d WHERE d.code = 'D02'
UNION ALL
SELECT d.id, 'Sahidbhumi Rural Municipality', 'सहिदभूमि गाउँपालिका', 'rural_municipality', 'D02-R03', 7 FROM public.districts d WHERE d.code = 'D02'
UNION ALL
SELECT d.id, 'Sangurigadhi Rural Municipality', 'सागुरीगढी गाउँपालिका', 'rural_municipality', 'D02-R04', 8 FROM public.districts d WHERE d.code = 'D02'
UNION ALL
SELECT d.id, 'Ilam Municipality', 'इलाम नगरपालिका', 'municipality', 'D03-M01', 12 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Deumai Municipality', 'देउमाई नगरपालिका', 'municipality', 'D03-M02', 9 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Mai Municipality', 'माई नगरपालिका', 'municipality', 'D03-M03', 12 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Suryodaya Municipality', 'सूर्योदय नगरपालिका', 'municipality', 'D03-M04', 14 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Chulachuli Rural Municipality', 'चुलाचुली गाउँपालिका', 'rural_municipality', 'D03-R01', 7 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Maijogmai Rural Municipality', 'माईजोगमाई गाउँपालिका', 'rural_municipality', 'D03-R02', 6 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Mangsebung Rural Municipality', 'माङसेबुङ गाउँपालिका', 'rural_municipality', 'D03-R03', 5 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Phakphokthum Rural Municipality', 'फाकफोकथुम गाउँपालिका', 'rural_municipality', 'D03-R04', 7 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Rong Rural Municipality', 'रोङ गाउँपालिका', 'rural_municipality', 'D03-R05', 6 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Sandakpur Rural Municipality', 'सन्दकपुर गाउँपालिका', 'rural_municipality', 'D03-R06', 6 FROM public.districts d WHERE d.code = 'D03'
UNION ALL
SELECT d.id, 'Mechinagar Municipality', 'मेचीनगर नगरपालिका', 'municipality', 'D04-M01', 15 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Bhadrapur Municipality', 'भद्रपुर नगरपालिका', 'municipality', 'D04-M02', 10 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Birtamod Municipality', 'बिर्तामोड नगरपालिका', 'municipality', 'D04-M03', 11 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Damak Municipality', 'दमक नगरपालिका', 'municipality', 'D04-M04', 11 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Kankai Municipality', 'कनकाई नगरपालिका', 'municipality', 'D04-M05', 9 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Shivasatakshi Municipality', 'शिवसताक्षी नगरपालिका', 'municipality', 'D04-M06', 11 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Arjundhara Municipality', 'अर्जुनधारा नगरपालिका', 'municipality', 'D04-M07', 9 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Gauradaha Municipality', 'गौरादह नगरपालिका', 'municipality', 'D04-M08', 9 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Bahradashi Rural Municipality', 'बाह्रदशी गाउँपालिका', 'rural_municipality', 'D04-R01', 8 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Buddhashanti Rural Municipality', 'बुद्धशान्ति गाउँपालिका', 'rural_municipality', 'D04-R02', 9 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Gaurigunj Rural Municipality', 'गौरीगंज गाउँपालिका', 'rural_municipality', 'D04-R03', 7 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Haldibari Rural Municipality', 'हल्दीबारी गाउँपालिका', 'rural_municipality', 'D04-R04', 7 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Jhapa Rural Municipality', 'झापा गाउँपालिका', 'rural_municipality', 'D04-R05', 7 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Kachankawal Rural Municipality', 'कचनकवल गाउँपालिका', 'rural_municipality', 'D04-R06', 9 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Kamal Rural Municipality', 'कमल गाउँपालिका', 'rural_municipality', 'D04-R07', 8 FROM public.districts d WHERE d.code = 'D04'
UNION ALL
SELECT d.id, 'Halesi Tuwachung Municipality', 'हलेसी तुवाचुङ नगरपालिका', 'municipality', 'D05-M01', 9 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Rupakot Majhuwagadhi Municipality', 'रुपाकोट मझुवागढी नगरपालिका', 'municipality', 'D05-M02', 9 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Diktel Rupakot Majhuwagadhi Municipality', 'दिक्तेल रुपाकोट मझुवागढी नगरपालिका', 'municipality', 'D05-M03', 10 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Aiselukharka Rural Municipality', 'ऐसेलुखर्क गाउँपालिका', 'rural_municipality', 'D05-R01', 6 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Barahapokhari Rural Municipality', 'बराहपोखरी गाउँपालिका', 'rural_municipality', 'D05-R02', 7 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Jantedhunga Rural Municipality', 'जन्तेढुंगा गाउँपालिका', 'rural_municipality', 'D05-R03', 6 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Khotehang Rural Municipality', 'खोटेहाङ गाउँपालिका', 'rural_municipality', 'D05-R04', 7 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Rawabesi Rural Municipality', 'रावाबेसी गाउँपालिका', 'rural_municipality', 'D05-R05', 6 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Sakela Rural Municipality', 'साकेला गाउँपालिका', 'rural_municipality', 'D05-R06', 6 FROM public.districts d WHERE d.code = 'D05'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Kepilasgadhi Rural Municipality', 'केपिलासगढी गाउँपालिका', 'rural_municipality', 'D05-R07', 5 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Lamidanda Rural Municipality', 'लामिडाँडा गाउँपालिका', 'rural_municipality', 'D05-R08', 5 FROM public.districts d WHERE d.code = 'D05'
UNION ALL
SELECT d.id, 'Biratnagar Metropolitan', 'विराटनगर महानगरपालिका', 'metropolitan', 'D06-MT01', 19 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Belbari Municipality', 'बेलवारी नगरपालिका', 'municipality', 'D06-M01', 11 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Urlabari Municipality', 'उर्लाबारी नगरपालिका', 'municipality', 'D06-M02', 11 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Rangeli Municipality', 'रंगेली नगरपालिका', 'municipality', 'D06-M03', 10 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Sundar Haraicha Municipality', 'सुन्दर हरैचा नगरपालिका', 'municipality', 'D06-M04', 12 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Pathari Shanishchare Municipality', 'पथरी शनिश्चरे नगरपालिका', 'municipality', 'D06-M05', 12 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Ratuwamai Municipality', 'रतुवामाई नगरपालिका', 'municipality', 'D06-M06', 11 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Letang Municipality', 'लेटाङ नगरपालिका', 'municipality', 'D06-M07', 10 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Sunawarshi Municipality', 'सुनवर्षि नगरपालिका', 'municipality', 'D06-M08', 9 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Budhiganga Rural Municipality', 'बुढीगंगा गाउँपालिका', 'rural_municipality', 'D06-R01', 7 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Dhanpalthan Rural Municipality', 'धनपालथान गाउँपालिका', 'rural_municipality', 'D06-R02', 7 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Gramthan Rural Municipality', 'ग्रामथान गाउँपालिका', 'rural_municipality', 'D06-R03', 7 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Jahada Rural Municipality', 'जहदा गाउँपालिका', 'rural_municipality', 'D06-R04', 5 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Kanepokhari Rural Municipality', 'कानेपोखरी गाउँपालिका', 'rural_municipality', 'D06-R05', 7 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Katahari Rural Municipality', 'कटहरी गाउँपालिका', 'rural_municipality', 'D06-R06', 8 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Kerabari Rural Municipality', 'केराबारी गाउँपालिका', 'rural_municipality', 'D06-R07', 7 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Miklajung Rural Municipality', 'मिक्लाजुङ गाउँपालिका', 'rural_municipality', 'D06-R08', 6 FROM public.districts d WHERE d.code = 'D06'
UNION ALL
SELECT d.id, 'Siddhicharan Municipality', 'सिद्धिचरण नगरपालिका', 'municipality', 'D07-M01', 9 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Champadevi Rural Municipality', 'चम्पादेवी गाउँपालिका', 'rural_municipality', 'D07-R01', 5 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Chisankhugadhi Rural Municipality', 'चिसंखुगढी गाउँपालिका', 'rural_municipality', 'D07-R02', 7 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Khijidemba Rural Municipality', 'खिजीदेम्बा गाउँपालिका', 'rural_municipality', 'D07-R03', 7 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Likhu Rural Municipality', 'लिखु गाउँपालिका', 'rural_municipality', 'D07-R04', 7 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Manebhanjyang Rural Municipality', 'मानेभञ्ज्याङ गाउँपालिका', 'rural_municipality', 'D07-R05', 5 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Molung Rural Municipality', 'मोलुङ गाउँपालिका', 'rural_municipality', 'D07-R06', 7 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Sunkoshi Rural Municipality', 'सुनकोशी गाउँपालिका', 'rural_municipality', 'D07-R07', 6 FROM public.districts d WHERE d.code = 'D07'
UNION ALL
SELECT d.id, 'Phidim Municipality', 'फिदिम नगरपालिका', 'municipality', 'D08-M01', 14 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Falgunanda Rural Municipality', 'फाल्गुनन्द गाउँपालिका', 'rural_municipality', 'D08-R01', 7 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Hilihang Rural Municipality', 'हिलिहाङ गाउँपालिका', 'rural_municipality', 'D08-R02', 6 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Kummayak Rural Municipality', 'कुम्मायक गाउँपालिका', 'rural_municipality', 'D08-R03', 5 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Miklajung Rural Municipality', 'मिक्लाजुङ गाउँपालिका', 'rural_municipality', 'D08-R04', 6 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Phalelung Rural Municipality', 'फालेलुङ गाउँपालिका', 'rural_municipality', 'D08-R05', 7 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Tumbewa Rural Municipality', 'तुम्बेवा गाउँपालिका', 'rural_municipality', 'D08-R06', 5 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Yangwarak Rural Municipality', 'याङवरक गाउँपालिका', 'rural_municipality', 'D08-R07', 6 FROM public.districts d WHERE d.code = 'D08'
UNION ALL
SELECT d.id, 'Khandbari Municipality', 'खाँदबारी नगरपालिका', 'municipality', 'D09-M01', 11 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Chainpur Municipality', 'चैनपुर नगरपालिका', 'municipality', 'D09-M02', 11 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Dharmadevi Municipality', 'धर्मदेवी नगरपालिका', 'municipality', 'D09-M03', 9 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Madi Municipality', 'माडी नगरपालिका', 'municipality', 'D09-M04', 9 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Panchkhapan Municipality', 'पाँचखपन नगरपालिका', 'municipality', 'D09-M05', 9 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Bhotkhola Rural Municipality', 'भोटखोला गाउँपालिका', 'rural_municipality', 'D09-R01', 5 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Chichila Rural Municipality', 'चिचिला गाउँपालिका', 'rural_municipality', 'D09-R02', 5 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Makalu Rural Municipality', 'मकालु गाउँपालिका', 'rural_municipality', 'D09-R03', 6 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Sabhapokhari Rural Municipality', 'सभापोखरी गाउँपालिका', 'rural_municipality', 'D09-R04', 6 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Silichong Rural Municipality', 'सिलीचोङ गाउँपालिका', 'rural_municipality', 'D09-R05', 5 FROM public.districts d WHERE d.code = 'D09'
UNION ALL
SELECT d.id, 'Solududhkunda Municipality', 'सोलुदुधकुण्ड नगरपालिका', 'municipality', 'D10-M01', 9 FROM public.districts d WHERE d.code = 'D10'
UNION ALL
SELECT d.id, 'Dudhauli Municipality', 'दुधकौशी गाउँपालिका', 'rural_municipality', 'D10-R01', 9 FROM public.districts d WHERE d.code = 'D10'
UNION ALL
SELECT d.id, 'Khumbu Pasanglhamu Rural Municipality', 'खुम्बु पासाङल्हामु गाउँपालिका', 'rural_municipality', 'D10-R02', 6 FROM public.districts d WHERE d.code = 'D10'
UNION ALL
SELECT d.id, 'Likhupike Rural Municipality', 'लिखुपिके गाउँपालिका', 'rural_municipality', 'D10-R03', 6 FROM public.districts d WHERE d.code = 'D10'
UNION ALL
SELECT d.id, 'Mahakulung Rural Municipality', 'महाकुलुङ गाउँपालिका', 'rural_municipality', 'D10-R04', 5 FROM public.districts d WHERE d.code = 'D10'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Mapya Dudhkoshi Rural Municipality', 'माप्य दुधकोशी गाउँपालिका', 'rural_municipality', 'D10-R05', 7 FROM public.districts d WHERE d.code = 'D10'
UNION ALL
SELECT d.id, 'Necha Salyan Rural Municipality', 'नेचासल्यान गाउँपालिका', 'rural_municipality', 'D10-R06', 5 FROM public.districts d WHERE d.code = 'D10'
UNION ALL
SELECT d.id, 'Thulung Dudhkoshi Rural Municipality', 'थुलुङ दुधकोशी गाउँपालिका', 'rural_municipality', 'D10-R07', 8 FROM public.districts d WHERE d.code = 'D10'
UNION ALL
SELECT d.id, 'Itahari Sub-Metropolitan', 'इटहरी उपमहानगरपालिका', 'sub_metropolitan', 'D11-SM01', 20 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Dharan Sub-Metropolitan', 'धरान उपमहानगरपालिका', 'sub_metropolitan', 'D11-SM02', 20 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Inaruwa Municipality', 'इनरुवा नगरपालिका', 'municipality', 'D11-M01', 12 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Duhabi Municipality', 'दुहवी नगरपालिका', 'municipality', 'D11-M02', 13 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Barahakshetra Municipality', 'बराहक्षेत्र नगरपालिका', 'municipality', 'D11-M03', 12 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Ramdhuni Municipality', 'रामधुनी नगरपालिका', 'municipality', 'D11-M04', 11 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Bhokraha Narsingh Rural Municipality', 'भोक्राहा नरसिंह गाउँपालिका', 'rural_municipality', 'D11-R01', 7 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Dewanganj Rural Municipality', 'देवानगञ्ज गाउँपालिका', 'rural_municipality', 'D11-R02', 6 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Gadhi Rural Municipality', 'गढी गाउँपालिका', 'rural_municipality', 'D11-R03', 6 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Harinagar Rural Municipality', 'हरिनगर गाउँपालिका', 'rural_municipality', 'D11-R04', 6 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Koshi Rural Municipality', 'कोशी गाउँपालिका', 'rural_municipality', 'D11-R05', 6 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Barju Rural Municipality', 'बर्जु गाउँपालिका', 'rural_municipality', 'D11-R06', 6 FROM public.districts d WHERE d.code = 'D11'
UNION ALL
SELECT d.id, 'Phungling Municipality', 'फुङलिङ नगरपालिका', 'municipality', 'D12-M01', 10 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Aathrai Tribeni Rural Municipality', 'आठराई त्रिवेणी गाउँपालिका', 'rural_municipality', 'D12-R01', 6 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Meringden Rural Municipality', 'मेरिङदेन गाउँपालिका', 'rural_municipality', 'D12-R02', 5 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Mikwakhola Rural Municipality', 'मिक्वाखोला गाउँपालिका', 'rural_municipality', 'D12-R03', 5 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Pathibhara Yangwarak Rural Municipality', 'पाथीभरा याङवरक गाउँपालिका', 'rural_municipality', 'D12-R04', 5 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Phaktanglung Rural Municipality', 'फक्ताङलुङ गाउँपालिका', 'rural_municipality', 'D12-R05', 7 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Sidingba Rural Municipality', 'सिदिङ्बा गाउँपालिका', 'rural_municipality', 'D12-R06', 5 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Sirijangha Rural Municipality', 'सिरीजङ्घा गाउँपालिका', 'rural_municipality', 'D12-R07', 5 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Maiwakhola Rural Municipality', 'मैवाखोला गाउँपालिका', 'rural_municipality', 'D12-R08', 5 FROM public.districts d WHERE d.code = 'D12'
UNION ALL
SELECT d.id, 'Myanglung Municipality', 'म्याङलुङ नगरपालिका', 'municipality', 'D13-M01', 10 FROM public.districts d WHERE d.code = 'D13'
UNION ALL
SELECT d.id, 'Laligurans Municipality', 'लालीगुराँस नगरपालिका', 'municipality', 'D13-M02', 9 FROM public.districts d WHERE d.code = 'D13'
UNION ALL
SELECT d.id, 'Aathrai Rural Municipality', 'आठराई गाउँपालिका', 'rural_municipality', 'D13-R01', 6 FROM public.districts d WHERE d.code = 'D13'
UNION ALL
SELECT d.id, 'Chhathar Rural Municipality', 'छथर गाउँपालिका', 'rural_municipality', 'D13-R02', 6 FROM public.districts d WHERE d.code = 'D13'
UNION ALL
SELECT d.id, 'Menchayam Rural Municipality', 'मेन्छायम गाउँपालिका', 'rural_municipality', 'D13-R03', 5 FROM public.districts d WHERE d.code = 'D13'
UNION ALL
SELECT d.id, 'Phedap Rural Municipality', 'फेदाप गाउँपालिका', 'rural_municipality', 'D13-R04', 7 FROM public.districts d WHERE d.code = 'D13'
UNION ALL
SELECT d.id, 'Triyuga Municipality', 'त्रियुगा नगरपालिका', 'municipality', 'D14-M01', 17 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Katari Municipality', 'कटारी नगरपालिका', 'municipality', 'D14-M02', 14 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Chaudandigadhi Municipality', 'चौदण्डीगढी नगरपालिका', 'municipality', 'D14-M03', 13 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Belaka Municipality', 'बेलका नगरपालिका', 'municipality', 'D14-M04', 10 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Udayapurgadhi Rural Municipality', 'उदयपुरगढी गाउँपालिका', 'rural_municipality', 'D14-R01', 9 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Rautamai Rural Municipality', 'रौतामाई गाउँपालिका', 'rural_municipality', 'D14-R02', 7 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Tapli Rural Municipality', 'ताप्ली गाउँपालिका', 'rural_municipality', 'D14-R03', 6 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Limchungbung Rural Municipality', 'लिम्चुङबुङ गाउँपालिका', 'rural_municipality', 'D14-R04', 5 FROM public.districts d WHERE d.code = 'D14'
UNION ALL
SELECT d.id, 'Rajbiraj Municipality', 'राजविराज नगरपालिका', 'municipality', 'D15-M01', 21 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Kanchanrup Municipality', 'कञ्चनरुप नगरपालिका', 'municipality', 'D15-M02', 11 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Dakneshwari Municipality', 'डाक्नेश्वरी नगरपालिका', 'municipality', 'D15-M03', 10 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Bodebarsain Municipality', 'बोदेबरसाइन नगरपालिका', 'municipality', 'D15-M04', 9 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Khadak Municipality', 'खडक नगरपालिका', 'municipality', 'D15-M05', 10 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Shambhunath Municipality', 'शम्भुनाथ नगरपालिका', 'municipality', 'D15-M06', 11 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Hanumannagar Kankalini Municipality', 'हनुमाननगर कंकालिनी नगरपालिका', 'municipality', 'D15-M07', 12 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Saptakoshi Municipality', 'सप्तकोशी नगरपालिका', 'municipality', 'D15-M08', 11 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Surunga Municipality', 'सुरुंगा नगरपालिका', 'municipality', 'D15-M09', 10 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Agnisaira Krishnasavaran Rural Municipality', 'अग्निसाइर कृष्णसवरन गाउँपालिका', 'rural_municipality', 'D15-R01', 8 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Balan Bihul Rural Municipality', 'बलान बिहुल गाउँपालिका', 'rural_municipality', 'D15-R02', 6 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Bishnupur Rural Municipality', 'विष्णुपुर गाउँपालिका', 'rural_municipality', 'D15-R03', 7 FROM public.districts d WHERE d.code = 'D15'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Chhinnamasta Rural Municipality', 'छिन्नमस्ता गाउँपालिका', 'rural_municipality', 'D15-R04', 8 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Mahadeva Rural Municipality', 'महादेवा गाउँपालिका', 'rural_municipality', 'D15-R05', 6 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Rupani Rural Municipality', 'रुपनी गाउँपालिका', 'rural_municipality', 'D15-R06', 7 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Rajgadh Rural Municipality', 'राजगढ गाउँपालिका', 'rural_municipality', 'D15-R07', 6 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Tilathi Koiladi Rural Municipality', 'तिलाठी कोइलाडी गाउँपालिका', 'rural_municipality', 'D15-R08', 9 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Tirhut Rural Municipality', 'तिरहुत गाउँपालिका', 'rural_municipality', 'D15-R09', 6 FROM public.districts d WHERE d.code = 'D15'
UNION ALL
SELECT d.id, 'Siraha Municipality', 'सिराहा नगरपालिका', 'municipality', 'D16-M01', 22 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Lahan Municipality', 'लहान नगरपालिका', 'municipality', 'D16-M02', 26 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Dhangadhimai Municipality', 'धनगढीमाई नगरपालिका', 'municipality', 'D16-M03', 13 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Mirchaiya Municipality', 'मिर्चैया नगरपालिका', 'municipality', 'D16-M04', 12 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Golbazar Municipality', 'गोलबजार नगरपालिका', 'municipality', 'D16-M05', 11 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Kalyanpur Municipality', 'कल्याणपुर नगरपालिका', 'municipality', 'D16-M06', 9 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Sukhipur Municipality', 'सुखीपुर नगरपालिका', 'municipality', 'D16-M07', 13 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Karjanha Municipality', 'कर्जन्हा नगरपालिका', 'municipality', 'D16-M08', 10 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Arnama Rural Municipality', 'अर्नमा गाउँपालिका', 'rural_municipality', 'D16-R01', 7 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Aurahi Rural Municipality', 'औरही गाउँपालिका', 'rural_municipality', 'D16-R02', 6 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Bariyarpatti Rural Municipality', 'बरियारपट्टी गाउँपालिका', 'rural_municipality', 'D16-R03', 6 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Bhagawanpur Rural Municipality', 'भगवानपुर गाउँपालिका', 'rural_municipality', 'D16-R04', 7 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Bishnupur Rural Municipality', 'विष्णुपुर गाउँपालिका', 'rural_municipality', 'D16-R05', 7 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Lakshmipur Patari Rural Municipality', 'लक्ष्मीपुर पतारी गाउँपालिका', 'rural_municipality', 'D16-R06', 6 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Naraha Rural Municipality', 'नरहा गाउँपालिका', 'rural_municipality', 'D16-R07', 6 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Navarajpur Rural Municipality', 'नवराजपुर गाउँपालिका', 'rural_municipality', 'D16-R08', 6 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Sakhuwanankar Katti Rural Municipality', 'सखुवानान्कर्कट्टी गाउँपालिका', 'rural_municipality', 'D16-R09', 6 FROM public.districts d WHERE d.code = 'D16'
UNION ALL
SELECT d.id, 'Janakpur Sub-Metropolitan', 'जनकपुर उपमहानगरपालिका', 'sub_metropolitan', 'D17-SM01', 25 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Chhireshwarnath Municipality', 'छिरेश्वरनाथ नगरपालिका', 'municipality', 'D17-M01', 11 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Ganeshman Charnath Municipality', 'गणेशमान चरनाथ नगरपालिका', 'municipality', 'D17-M02', 9 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Dhanushadham Municipality', 'धनुषाधाम नगरपालिका', 'municipality', 'D17-M03', 13 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Nagarain Municipality', 'नगराइन नगरपालिका', 'municipality', 'D17-M04', 10 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Bideha Municipality', 'विदेह नगरपालिका', 'municipality', 'D17-M05', 11 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Mithila Municipality', 'मिथिला नगरपालिका', 'municipality', 'D17-M06', 11 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Sabaila Municipality', 'सबैला नगरपालिका', 'municipality', 'D17-M07', 13 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Kamala Municipality', 'कमला नगरपालिका', 'municipality', 'D17-M08', 9 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Shahidnagar Municipality', 'शहीदनगर नगरपालिका', 'municipality', 'D17-M09', 12 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Mithila Bihari Municipality', 'मिथिला बिहारी नगरपालिका', 'municipality', 'D17-M10', 9 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Hansapur Municipality', 'हंसपुर नगरपालिका', 'municipality', 'D17-M11', 9 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Janaknandini Rural Municipality', 'जनकनन्दिनी गाउँपालिका', 'rural_municipality', 'D17-R01', 7 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Bateshwar Rural Municipality', 'बटेश्वर गाउँपालिका', 'rural_municipality', 'D17-R02', 7 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Mukhiyapatti Musaharmiya Rural Municipality', 'मुखियापट्टी मुसहरमिया गाउँपालिका', 'rural_municipality', 'D17-R03', 7 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Lakshminiya Rural Municipality', 'लक्ष्मीनिया गाउँपालिका', 'rural_municipality', 'D17-R04', 7 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Aurahi Rural Municipality', 'औरही गाउँपालिका', 'rural_municipality', 'D17-R05', 5 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Dhanauji Rural Municipality', 'धनौजी गाउँपालिका', 'rural_municipality', 'D17-R06', 6 FROM public.districts d WHERE d.code = 'D17'
UNION ALL
SELECT d.id, 'Jaleshwar Municipality', 'जलेश्वर नगरपालिका', 'municipality', 'D18-M01', 11 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Bardibas Municipality', 'बर्दिबास नगरपालिका', 'municipality', 'D18-M02', 17 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Gaushala Municipality', 'गौशाला नगरपालिका', 'municipality', 'D18-M03', 13 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Loharpatti Municipality', 'लोहरपट्टी नगरपालिका', 'municipality', 'D18-M04', 9 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Ramgopalpur Municipality', 'रामगोपालपुर नगरपालिका', 'municipality', 'D18-M05', 8 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Manara Shiswa Municipality', 'मनरा शिसवा नगरपालिका', 'municipality', 'D18-M06', 8 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Matihani Municipality', 'मटिहानी नगरपालिका', 'municipality', 'D18-M07', 9 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Bhangaha Municipality', 'भंगाहा नगरपालिका', 'municipality', 'D18-M08', 10 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Balawa Municipality', 'बलवा नगरपालिका', 'municipality', 'D18-M09', 9 FROM public.districts d WHERE d.code = 'D18'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Aurahi Municipality', 'औरही नगरपालिका', 'municipality', 'D18-M10', 9 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Ekdara Rural Municipality', 'एकडारा गाउँपालिका', 'rural_municipality', 'D18-R01', 7 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Mahottari Rural Municipality', 'महोत्तरी गाउँपालिका', 'rural_municipality', 'D18-R02', 6 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Pipara Rural Municipality', 'पिपरा गाउँपालिका', 'rural_municipality', 'D18-R03', 6 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Samsi Rural Municipality', 'साम्सी गाउँपालिका', 'rural_municipality', 'D18-R04', 6 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Sonama Rural Municipality', 'सोनमा गाउँपालिका', 'rural_municipality', 'D18-R05', 7 FROM public.districts d WHERE d.code = 'D18'
UNION ALL
SELECT d.id, 'Malangwa Municipality', 'मलंगवा नगरपालिका', 'municipality', 'D19-M01', 17 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Lalbandi Municipality', 'लालबन्दी नगरपालिका', 'municipality', 'D19-M02', 13 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Hariwan Municipality', 'हरिवन नगरपालिका', 'municipality', 'D19-M03', 15 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Ishworpur Municipality', 'ईश्वरपुर नगरपालिका', 'municipality', 'D19-M04', 11 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Godaita Municipality', 'गोडैता नगरपालिका', 'municipality', 'D19-M05', 11 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Bagmati Municipality', 'बागमती नगरपालिका', 'municipality', 'D19-M06', 15 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Barahathwa Municipality', 'बरहथवा नगरपालिका', 'municipality', 'D19-M07', 14 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Haripur Municipality', 'हरिपुर नगरपालिका', 'municipality', 'D19-M08', 10 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Balara Municipality', 'बलरा नगरपालिका', 'municipality', 'D19-M09', 8 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Haripurwa Municipality', 'हरिपुर्वा नगरपालिका', 'municipality', 'D19-M10', 8 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Kabilasi Municipality', 'कविलासी नगरपालिका', 'municipality', 'D19-M11', 8 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Brahampuri Rural Municipality', 'ब्रह्मपुरी गाउँपालिका', 'rural_municipality', 'D19-R01', 7 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Basbariya Rural Municipality', 'बसबरिया गाउँपालिका', 'rural_municipality', 'D19-R02', 7 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Bishnu Rural Municipality', 'विष्णु गाउँपालिका', 'rural_municipality', 'D19-R03', 6 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Chandranagar Rural Municipality', 'चन्द्रनगर गाउँपालिका', 'rural_municipality', 'D19-R04', 7 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Chakraghatta Rural Municipality', 'चक्रघट्टा गाउँपालिका', 'rural_municipality', 'D19-R05', 6 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Dhankaul Rural Municipality', 'धनकौल गाउँपालिका', 'rural_municipality', 'D19-R06', 5 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Kaudena Rural Municipality', 'कौडेना गाउँपालिका', 'rural_municipality', 'D19-R07', 6 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Parsa Rural Municipality', 'पर्सा गाउँपालिका', 'rural_municipality', 'D19-R08', 6 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Ramnagar Rural Municipality', 'रामनगर गाउँपालिका', 'rural_municipality', 'D19-R09', 5 FROM public.districts d WHERE d.code = 'D19'
UNION ALL
SELECT d.id, 'Kalaiya Sub-Metropolitan', 'कलैया उपमहानगरपालिका', 'sub_metropolitan', 'D20-SM01', 27 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Jitpur Simara Sub-Metropolitan', 'जीतपुर सिमरा उपमहानगरपालिका', 'sub_metropolitan', 'D20-SM02', 23 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Kolhabi Municipality', 'कोल्हवी नगरपालिका', 'municipality', 'D20-M01', 12 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Nijgadh Municipality', 'निजगढ नगरपालिका', 'municipality', 'D20-M02', 11 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Simraungadh Municipality', 'सिम्रौनगढ नगरपालिका', 'municipality', 'D20-M03', 15 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Pachrauta Municipality', 'पचरौता नगरपालिका', 'municipality', 'D20-M04', 10 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Mahagadhimai Municipality', 'महागढीमाई नगरपालिका', 'municipality', 'D20-M05', 13 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Adarsha Kotwal Rural Municipality', 'आदर्श कोटवाल गाउँपालिका', 'rural_municipality', 'D20-R01', 9 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Baragadhi Rural Municipality', 'बारागढी गाउँपालिका', 'rural_municipality', 'D20-R02', 7 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Bishrampur Rural Municipality', 'विश्रामपुर गाउँपालिका', 'rural_municipality', 'D20-R03', 6 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Devtal Rural Municipality', 'देवताल गाउँपालिका', 'rural_municipality', 'D20-R04', 6 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Karaiyamai Rural Municipality', 'करैयामाई गाउँपालिका', 'rural_municipality', 'D20-R05', 7 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Pheta Rural Municipality', 'फेटा गाउँपालिका', 'rural_municipality', 'D20-R06', 7 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Parawanipur Rural Municipality', 'परवानीपुर गाउँपालिका', 'rural_municipality', 'D20-R07', 6 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Prasauni Rural Municipality', 'प्रसौनी गाउँपालिका', 'rural_municipality', 'D20-R08', 6 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Suwarna Rural Municipality', 'सुवर्ण गाउँपालिका', 'rural_municipality', 'D20-R09', 8 FROM public.districts d WHERE d.code = 'D20'
UNION ALL
SELECT d.id, 'Birgunj Metropolitan', 'वीरगञ्ज महानगरपालिका', 'metropolitan', 'D21-MT01', 32 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Pokhariya Municipality', 'पोखरिया नगरपालिका', 'municipality', 'D21-M01', 13 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Bahudarmai Municipality', 'बहुदरमाई नगरपालिका', 'municipality', 'D21-M02', 11 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Parsagadhi Municipality', 'पर्सागढी नगरपालिका', 'municipality', 'D21-M03', 15 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Bindabasini Rural Municipality', 'बिन्दबासिनी गाउँपालिका', 'rural_municipality', 'D21-R01', 8 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Chhipaharmai Rural Municipality', 'छिपहरमाई गाउँपालिका', 'rural_municipality', 'D21-R02', 6 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Dhobini Rural Municipality', 'ढोबिनी गाउँपालिका', 'rural_municipality', 'D21-R03', 6 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Jagarnathpur Rural Municipality', 'जगरनाथपुर गाउँपालिका', 'rural_municipality', 'D21-R04', 7 FROM public.districts d WHERE d.code = 'D21'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Kalikamai Rural Municipality', 'कालिकामाई गाउँपालिका', 'rural_municipality', 'D21-R05', 7 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Pakaha Mainpur Rural Municipality', 'पकाहा मैनपुर गाउँपालिका', 'rural_municipality', 'D21-R06', 7 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Paterwa Sugauli Rural Municipality', 'पटेर्वा सुगौली गाउँपालिका', 'rural_municipality', 'D21-R07', 7 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Sakhuwa Prasauni Rural Municipality', 'सखुवा प्रसौनी गाउँपालिका', 'rural_municipality', 'D21-R08', 7 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Thori Rural Municipality', 'ठोरी गाउँपालिका', 'rural_municipality', 'D21-R09', 6 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Jirabhawani Rural Municipality', 'जिराभवानी गाउँपालिका', 'rural_municipality', 'D21-R10', 5 FROM public.districts d WHERE d.code = 'D21'
UNION ALL
SELECT d.id, 'Gaur Municipality', 'गौर नगरपालिका', 'municipality', 'D22-M01', 23 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Chandrapur Municipality', 'चन्द्रपुर नगरपालिका', 'municipality', 'D22-M02', 13 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Garuda Municipality', 'गरुडा नगरपालिका', 'municipality', 'D22-M03', 11 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Baudhimai Municipality', 'बौधीमाई नगरपालिका', 'municipality', 'D22-M04', 13 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Brindaban Municipality', 'वृन्दावन नगरपालिका', 'municipality', 'D22-M05', 9 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Dewahi Gonahi Municipality', 'देवाही गोनाही नगरपालिका', 'municipality', 'D22-M06', 11 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Gujara Municipality', 'गुजरा नगरपालिका', 'municipality', 'D22-M07', 9 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Ishnath Municipality', 'ईशनाथ नगरपालिका', 'municipality', 'D22-M08', 10 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Katahariya Municipality', 'कटहरिया नगरपालिका', 'municipality', 'D22-M09', 9 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Madhav Narayan Municipality', 'माधव नारायण नगरपालिका', 'municipality', 'D22-M10', 10 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Maulapur Municipality', 'मौलापुर नगरपालिका', 'municipality', 'D22-M11', 8 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Paroha Municipality', 'परोहा नगरपालिका', 'municipality', 'D22-M12', 12 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Phatuwa Bijayapur Municipality', 'फतुवा विजयपुर नगरपालिका', 'municipality', 'D22-M13', 10 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Rajdevi Municipality', 'राजदेवी नगरपालिका', 'municipality', 'D22-M14', 9 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Rajpur Municipality', 'राजपुर नगरपालिका', 'municipality', 'D22-M15', 9 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Durga Bhagwati Rural Municipality', 'दुर्गा भगवती गाउँपालिका', 'rural_municipality', 'D22-R01', 6 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Yamunamai Rural Municipality', 'यमुनामाई गाउँपालिका', 'rural_municipality', 'D22-R02', 6 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Gadhimai Rural Municipality', 'गढीमाई गाउँपालिका', 'rural_municipality', 'D22-R03', 9 FROM public.districts d WHERE d.code = 'D22'
UNION ALL
SELECT d.id, 'Kathmandu Metropolitan', 'काठमाडौं महानगरपालिका', 'metropolitan', 'D28-MT01', 32 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Budhanilkantha Municipality', 'बुढानिलकण्ठ नगरपालिका', 'municipality', 'D28-M01', 13 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Chandragiri Municipality', 'चन्द्रागिरी नगरपालिका', 'municipality', 'D28-M02', 15 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Dakshinkali Municipality', 'दक्षिणकाली नगरपालिका', 'municipality', 'D28-M03', 9 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Gokarneshwor Municipality', 'गोकर्णेश्वर नगरपालिका', 'municipality', 'D28-M04', 9 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Kageshwori Manohara Municipality', 'कागेश्वरी मनोहरा नगरपालिका', 'municipality', 'D28-M05', 9 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Kirtipur Municipality', 'कीर्तिपुर नगरपालिका', 'municipality', 'D28-M06', 10 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Nagarjun Municipality', 'नागार्जुन नगरपालिका', 'municipality', 'D28-M07', 10 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Shankharapur Municipality', 'शंखरापुर नगरपालिका', 'municipality', 'D28-M08', 9 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Tarakeshwor Municipality', 'तारकेश्वर नगरपालिका', 'municipality', 'D28-M09', 11 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Tokha Municipality', 'टोखा नगरपालिका', 'municipality', 'D28-M10', 11 FROM public.districts d WHERE d.code = 'D28'
UNION ALL
SELECT d.id, 'Lalitpur Metropolitan', 'ललितपुर महानगरपालिका', 'metropolitan', 'D30-MT01', 29 FROM public.districts d WHERE d.code = 'D30'
UNION ALL
SELECT d.id, 'Godawari Municipality', 'गोदावरी नगरपालिका', 'municipality', 'D30-M01', 14 FROM public.districts d WHERE d.code = 'D30'
UNION ALL
SELECT d.id, 'Mahalaxmi Municipality', 'महालक्ष्मी नगरपालिका', 'municipality', 'D30-M02', 10 FROM public.districts d WHERE d.code = 'D30'
UNION ALL
SELECT d.id, 'Bagmati Rural Municipality', 'बागमती गाउँपालिका', 'rural_municipality', 'D30-R01', 9 FROM public.districts d WHERE d.code = 'D30'
UNION ALL
SELECT d.id, 'Konjyosom Rural Municipality', 'कोन्ज्योसोम गाउँपालिका', 'rural_municipality', 'D30-R02', 7 FROM public.districts d WHERE d.code = 'D30'
UNION ALL
SELECT d.id, 'Mahankal Rural Municipality', 'महाङ्काल गाउँपालिका', 'rural_municipality', 'D30-R03', 7 FROM public.districts d WHERE d.code = 'D30'
UNION ALL
SELECT d.id, 'Bhaktapur Municipality', 'भक्तपुर नगरपालिका', 'municipality', 'D26-M01', 10 FROM public.districts d WHERE d.code = 'D26'
UNION ALL
SELECT d.id, 'Madhyapur Thimi Municipality', 'मध्यपुर थिमी नगरपालिका', 'municipality', 'D26-M02', 9 FROM public.districts d WHERE d.code = 'D26'
UNION ALL
SELECT d.id, 'Suryabinayak Municipality', 'सूर्यविनायक नगरपालिका', 'municipality', 'D26-M03', 10 FROM public.districts d WHERE d.code = 'D26'
UNION ALL
SELECT d.id, 'Changunarayan Municipality', 'चाँगुनारायण नगरपालिका', 'municipality', 'D26-M04', 9 FROM public.districts d WHERE d.code = 'D26'
UNION ALL
SELECT d.id, 'Bharatpur Metropolitan', 'भरतपुर महानगरपालिका', 'metropolitan', 'D34-MT01', 29 FROM public.districts d WHERE d.code = 'D34'
UNION ALL
SELECT d.id, 'Kalika Municipality', 'कालिका नगरपालिका', 'municipality', 'D34-M01', 11 FROM public.districts d WHERE d.code = 'D34'
UNION ALL
SELECT d.id, 'Khairahani Municipality', 'खैरहनी नगरपालिका', 'municipality', 'D34-M02', 13 FROM public.districts d WHERE d.code = 'D34'
UNION ALL
SELECT d.id, 'Madi Municipality', 'माडी नगरपालिका', 'municipality', 'D34-M03', 10 FROM public.districts d WHERE d.code = 'D34'
UNION ALL
SELECT d.id, 'Rapti Municipality', 'राप्ती नगरपालिका', 'municipality', 'D34-M04', 15 FROM public.districts d WHERE d.code = 'D34'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Ratnanagar Municipality', 'रत्ननगर नगरपालिका', 'municipality', 'D34-M05', 16 FROM public.districts d WHERE d.code = 'D34'
UNION ALL
SELECT d.id, 'Ichchhakamana Rural Municipality', 'इच्छाकामना गाउँपालिका', 'rural_municipality', 'D34-R01', 6 FROM public.districts d WHERE d.code = 'D34'
UNION ALL
SELECT d.id, 'Pokhara Metropolitan', 'पोखरा महानगरपालिका', 'metropolitan', 'D39-MT01', 33 FROM public.districts d WHERE d.code = 'D39'
UNION ALL
SELECT d.id, 'Annapurna Rural Municipality', 'अन्नपूर्ण गाउँपालिका', 'rural_municipality', 'D39-R01', 11 FROM public.districts d WHERE d.code = 'D39'
UNION ALL
SELECT d.id, 'Machhapuchchhre Rural Municipality', 'माछापुच्छ्रे गाउँपालिका', 'rural_municipality', 'D39-R02', 9 FROM public.districts d WHERE d.code = 'D39'
UNION ALL
SELECT d.id, 'Madi Rural Municipality', 'मादी गाउँपालिका', 'rural_municipality', 'D39-R03', 12 FROM public.districts d WHERE d.code = 'D39'
UNION ALL
SELECT d.id, 'Rupa Rural Municipality', 'रुपा गाउँपालिका', 'rural_municipality', 'D39-R04', 7 FROM public.districts d WHERE d.code = 'D39'
UNION ALL
SELECT d.id, 'Butwal Sub-Metropolitan', 'बुटवल उपमहानगरपालिका', 'sub_metropolitan', 'D58-SM01', 19 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Siddharthanagar Municipality', 'सिद्धार्थनगर नगरपालिका', 'municipality', 'D58-M01', 13 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Devdaha Municipality', 'देवदह नगरपालिका', 'municipality', 'D58-M02', 12 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Lumbini Sanskritik Municipality', 'लुम्बिनी सांस्कृतिक नगरपालिका', 'municipality', 'D58-M03', 10 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Sainamaina Municipality', 'सैनामैना नगरपालिका', 'municipality', 'D58-M04', 12 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Tilottama Municipality', 'तिलोत्तमा नगरपालिका', 'municipality', 'D58-M05', 17 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Gaidahawa Rural Municipality', 'गैडहवा गाउँपालिका', 'rural_municipality', 'D58-R01', 7 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Kanchan Rural Municipality', 'कञ्चन गाउँपालिका', 'rural_municipality', 'D58-R02', 6 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Kotahimai Rural Municipality', 'कोटहीमाई गाउँपालिका', 'rural_municipality', 'D58-R03', 7 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Marchawari Rural Municipality', 'मर्चवारी गाउँपालिका', 'rural_municipality', 'D58-R04', 6 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Mayadevi Rural Municipality', 'मायादेवी गाउँपालिका', 'rural_municipality', 'D58-R05', 6 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Omsatiya Rural Municipality', 'ओमसतिया गाउँपालिका', 'rural_municipality', 'D58-R06', 5 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Rohini Rural Municipality', 'रोहिणी गाउँपालिका', 'rural_municipality', 'D58-R07', 6 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Sammarimai Rural Municipality', 'सम्मरीमाई गाउँपालिका', 'rural_municipality', 'D58-R08', 5 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Siyari Rural Municipality', 'सियारी गाउँपालिका', 'rural_municipality', 'D58-R09', 6 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Suddhodhan Rural Municipality', 'शुद्धोधन गाउँपालिका', 'rural_municipality', 'D58-R10', 6 FROM public.districts d WHERE d.code = 'D58'
UNION ALL
SELECT d.id, 'Ghorahi Sub-Metropolitan', 'घोराही उपमहानगरपालिका', 'sub_metropolitan', 'D50-SM01', 19 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Tulsipur Sub-Metropolitan', 'तुल्सीपुर उपमहानगरपालिका', 'sub_metropolitan', 'D50-SM02', 24 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Lamahi Municipality', 'लमही नगरपालिका', 'municipality', 'D50-M01', 10 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Babai Rural Municipality', 'बबई गाउँपालिका', 'rural_municipality', 'D50-R01', 7 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Banglachuli Rural Municipality', 'बंगलाचुली गाउँपालिका', 'rural_municipality', 'D50-R02', 9 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Dangisharan Rural Municipality', 'दंगीशरण गाउँपालिका', 'rural_municipality', 'D50-R03', 5 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Gadhawa Rural Municipality', 'गढवा गाउँपालिका', 'rural_municipality', 'D50-R04', 8 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Rajpur Rural Municipality', 'राजपुर गाउँपालिका', 'rural_municipality', 'D50-R05', 6 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Rapti Rural Municipality', 'राप्ती गाउँपालिका', 'rural_municipality', 'D50-R06', 8 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Shantinagar Rural Municipality', 'शान्तिनगर गाउँपालिका', 'rural_municipality', 'D50-R07', 6 FROM public.districts d WHERE d.code = 'D50'
UNION ALL
SELECT d.id, 'Nepalgunj Sub-Metropolitan', 'नेपालगन्ज उपमहानगरपालिका', 'sub_metropolitan', 'D48-SM01', 23 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Kohalpur Municipality', 'कोहलपुर नगरपालिका', 'municipality', 'D48-M01', 15 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Baijanath Rural Municipality', 'बैजनाथ गाउँपालिका', 'rural_municipality', 'D48-R01', 10 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Duduwa Rural Municipality', 'डुडुवा गाउँपालिका', 'rural_municipality', 'D48-R02', 7 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Janaki Rural Municipality', 'जानकी गाउँपालिका', 'rural_municipality', 'D48-R03', 6 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Khajura Rural Municipality', 'खजुरा गाउँपालिका', 'rural_municipality', 'D48-R04', 9 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Narainapur Rural Municipality', 'नरैनापुर गाउँपालिका', 'rural_municipality', 'D48-R05', 6 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Rapti Sonari Rural Municipality', 'राप्ती सोनारी गाउँपालिका', 'rural_municipality', 'D48-R06', 9 FROM public.districts d WHERE d.code = 'D48'
UNION ALL
SELECT d.id, 'Birendranagar Municipality', 'वीरेन्द्रनगर नगरपालिका', 'municipality', 'D67-M01', 16 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Bheriganga Municipality', 'भेरीगंगा नगरपालिका', 'municipality', 'D67-M02', 14 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Gurbhakot Municipality', 'गुर्भाकोट नगरपालिका', 'municipality', 'D67-M03', 13 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Lekbesi Municipality', 'लेकबेसी नगरपालिका', 'municipality', 'D67-M04', 11 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Panchpuri Municipality', 'पञ्चपुरी नगरपालिका', 'municipality', 'D67-M05', 9 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Barahatal Rural Municipality', 'बराहताल गाउँपालिका', 'rural_municipality', 'D67-R01', 6 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Chaukune Rural Municipality', 'चौकुने गाउँपालिका', 'rural_municipality', 'D67-R02', 5 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Chingad Rural Municipality', 'चिङगाड गाउँपालिका', 'rural_municipality', 'D67-R03', 6 FROM public.districts d WHERE d.code = 'D67'
UNION ALL
SELECT d.id, 'Simta Rural Municipality', 'सिम्ता गाउँपालिका', 'rural_municipality', 'D67-R04', 8 FROM public.districts d WHERE d.code = 'D67'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;

INSERT INTO public.palikas (district_id, name_en, name_ne, type, code, total_wards)
SELECT d.id, 'Dhangadhi Sub-Metropolitan', 'धनगढी उपमहानगरपालिका', 'sub_metropolitan', 'D77-SM01', 19 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Tikapur Municipality', 'टिकापुर नगरपालिका', 'municipality', 'D77-M01', 9 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Ghodaghodi Municipality', 'घोडाघोडी नगरपालिका', 'municipality', 'D77-M02', 12 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Lamkichuha Municipality', 'लम्कीचुहा नगरपालिका', 'municipality', 'D77-M03', 9 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Bhajani Municipality', 'भजनी नगरपालिका', 'municipality', 'D77-M04', 9 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Godawari Municipality', 'गोदावरी नगरपालिका', 'municipality', 'D77-M05', 12 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Gauriganga Municipality', 'गौरीगंगा नगरपालिका', 'municipality', 'D77-M06', 10 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Bardagoriya Rural Municipality', 'बर्दगोरिया गाउँपालिका', 'rural_municipality', 'D77-R01', 6 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Chure Rural Municipality', 'चुरे गाउँपालिका', 'rural_municipality', 'D77-R02', 6 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Janaki Rural Municipality', 'जानकी गाउँपालिका', 'rural_municipality', 'D77-R03', 6 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Joshipur Rural Municipality', 'जोशीपुर गाउँपालिका', 'rural_municipality', 'D77-R04', 6 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Kailari Rural Municipality', 'कैलारी गाउँपालिका', 'rural_municipality', 'D77-R05', 7 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Mohanyal Rural Municipality', 'मोहन्याल गाउँपालिका', 'rural_municipality', 'D77-R06', 5 FROM public.districts d WHERE d.code = 'D77'
UNION ALL
SELECT d.id, 'Bhimdatta Municipality', 'भीमदत्त नगरपालिका', 'municipality', 'D76-M01', 19 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Punarbas Municipality', 'पुनर्वास नगरपालिका', 'municipality', 'D76-M02', 11 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Bedkot Municipality', 'बेदकोट नगरपालिका', 'municipality', 'D76-M03', 10 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Belauri Municipality', 'बेलौरी नगरपालिका', 'municipality', 'D76-M04', 10 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Mahakali Municipality', 'महाकाली नगरपालिका', 'municipality', 'D76-M05', 10 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Shuklaphanta Municipality', 'शुक्लाफाँटा नगरपालिका', 'municipality', 'D76-M06', 11 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Krishnapur Municipality', 'कृष्णपुर नगरपालिका', 'municipality', 'D76-M07', 9 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Beldandi Rural Municipality', 'बेल्डाँडी गाउँपालिका', 'rural_municipality', 'D76-R01', 5 FROM public.districts d WHERE d.code = 'D76'
UNION ALL
SELECT d.id, 'Laljhadi Rural Municipality', 'लालझाडी गाउँपालिका', 'rural_municipality', 'D76-R02', 6 FROM public.districts d WHERE d.code = 'D76'
ON CONFLICT (code) DO UPDATE SET
  district_id = EXCLUDED.district_id,
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  type = EXCLUDED.type,
  total_wards = EXCLUDED.total_wards;
