-- =====================================================================
-- RBAC — roles (permissions + role_permissions are handled by migration 20250127000008)
-- Generated by database/scripts/dump-seeds-to-sql.ts — do not edit by hand.
-- Regenerate by re-running the generator; the file is deleted after commit.
-- =====================================================================

-- Roles (6) — idempotent; base roles are also inserted by migration 20250126000004 --
INSERT INTO public.roles (name, description) VALUES
  ('super_admin', 'Full system access across all palikas'),
  ('palika_admin', 'Full access within assigned palika'),
  ('content_editor', 'Can create and edit content'),
  ('content_reviewer', 'Can review and approve content'),
  ('support_agent', 'Can handle support tickets'),
  ('moderator', 'Can moderate content and users')
ON CONFLICT (name) DO NOTHING;
