-- =====================================================================
-- Categories — global content categories (heritage/event/blog/business) + per-palika business types
-- Generated by database/scripts/dump-seeds-to-sql.ts — do not edit by hand.
-- Regenerate by re-running the generator; the file is deleted after commit.
-- =====================================================================

-- Global categories (palika_id = NULL) from seed-database.ts (26) --
-- Uses WHERE NOT EXISTS because the unique index (palika_id, entity_type, slug)
-- does not uniquify NULL palika_id across rows.
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'heritage_site', 'Temple', 'मन्दिर', 'temple', 1
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'heritage_site' AND slug = 'temple'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'heritage_site', 'Monastery', 'गुम्बा', 'monastery', 2
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'heritage_site' AND slug = 'monastery'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'heritage_site', 'Palace', 'दरबार', 'palace', 3
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'heritage_site' AND slug = 'palace'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'heritage_site', 'Fort', 'किल्ला', 'fort', 4
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'heritage_site' AND slug = 'fort'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'heritage_site', 'Museum', 'संग्रहालय', 'museum', 5
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'heritage_site' AND slug = 'museum'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'heritage_site', 'Archaeological Site', 'पुरातत्व स्थल', 'archaeological', 6
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'heritage_site' AND slug = 'archaeological'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'heritage_site', 'Natural Heritage', 'प्राकृतिक सम्पदा', 'natural', 7
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'heritage_site' AND slug = 'natural'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'event', 'Festival', 'चाड पर्व', 'festival', 1
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'event' AND slug = 'festival'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'event', 'Cultural', 'सांस्कृतिक', 'cultural', 2
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'event' AND slug = 'cultural'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'event', 'Sports', 'खेलकुद', 'sports', 3
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'event' AND slug = 'sports'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'event', 'Religious', 'धार्मिक', 'religious', 4
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'event' AND slug = 'religious'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'event', 'Food', 'खाना', 'food', 5
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'event' AND slug = 'food'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'event', 'Music', 'संगीत', 'music', 6
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'event' AND slug = 'music'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'event', 'Educational', 'शैक्षिक', 'educational', 7
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'event' AND slug = 'educational'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'business', 'Accommodation', 'बास स्थान', 'accommodation', 1
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'business' AND slug = 'accommodation'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'business', 'Restaurant', 'रेस्टुरेन्ट', 'restaurant', 2
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'business' AND slug = 'restaurant'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'business', 'Tour Operator', 'भ्रमण संचालक', 'tour-operator', 3
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'business' AND slug = 'tour-operator'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'business', 'Transport', 'यातायात', 'transport', 4
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'business' AND slug = 'transport'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'business', 'Shopping', 'किनमेल', 'shopping', 5
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'business' AND slug = 'shopping'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'business', 'Entertainment', 'मनोरञ्जन', 'entertainment', 6
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'business' AND slug = 'entertainment'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'business', 'Government Office', 'सरकारी कार्यालय', 'government', 8
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'business' AND slug = 'government'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'blog_post', 'Tourism News', 'पर्यटन समाचार', 'tourism-news', 1
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'blog_post' AND slug = 'tourism-news'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'blog_post', 'Cultural Stories', 'सांस्कृतिक कथा', 'cultural-stories', 2
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'blog_post' AND slug = 'cultural-stories'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'blog_post', 'Local Events', 'स्थानीय कार्यक्रम', 'local-events', 3
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'blog_post' AND slug = 'local-events'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'blog_post', 'Heritage Updates', 'सम्पदा अपडेट', 'heritage-updates', 4
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'blog_post' AND slug = 'heritage-updates'
);
INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, display_order)
SELECT NULL, 'blog_post', 'Community News', 'समुदायिक समाचार', 'community-news', 5
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories
  WHERE palika_id IS NULL AND entity_type = 'blog_post' AND slug = 'community-news'
);

-- Per-palika business-type categories from seed-business-types.ts.
-- Required: supabase-business-targeting-datasource.ts filters categories by palika_id.
-- One row per (palika, business_type). Uses UPSERT on the (palika_id, entity_type, slug) unique constraint.

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Accommodation', 'आवास', 'accommodation', 'Hotels, lodges, guest houses, and other lodging facilities', 1
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Food & Beverage', 'खाना र पेय', 'food_beverage', 'Restaurants, cafes, bars, and food services', 2
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Producer', 'उत्पादक', 'producer', 'Agricultural producers and food manufacturers', 3
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Tour Guide', 'भ्रमण गाइड', 'tour_guide', 'Tour operators and professional guides', 4
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Professional Service', 'पेशेवर सेवा', 'professional_service', 'Consulting, planning, and professional services', 5
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Artisan Workshop', 'शिल्पी कार्यशाला', 'artisan_workshop', 'Craft studios and artisan producers', 6
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Transportation', 'परिवहन', 'transportation', 'Transportation and logistics services', 7
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;

INSERT INTO public.categories (palika_id, entity_type, name_en, name_ne, slug, description, display_order)
SELECT p.id, 'business', 'Retail Shop', 'खुद्रा दोकान', 'retail_shop', 'Retail stores and shopping services', 8
FROM public.palikas p
ON CONFLICT (palika_id, entity_type, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;
