-- =====================================================================
-- Business Categories — global registry (business_categories table)
-- Generated by database/scripts/dump-seeds-to-sql.ts — do not edit by hand.
-- Regenerate by re-running the generator; the file is deleted after commit.
-- =====================================================================

-- business_categories (8) — ported from seed-business-categories-direct.ts --
INSERT INTO public.business_categories (name_en, name_ne, slug, description, display_order) VALUES
  ('Accommodation', 'आवास', 'accommodation', 'Hotels, lodges, guest houses, and other lodging facilities', 1),
  ('Food & Beverage', 'खाना र पेय', 'food_beverage', 'Restaurants, cafes, bars, and food services', 2),
  ('Producer', 'उत्पादक', 'producer', 'Agricultural producers and food manufacturers', 3),
  ('Tour Guide', 'भ्रमण गाइड', 'tour_guide', 'Tour operators and professional guides', 4),
  ('Professional Service', 'पेशेवर सेवा', 'professional_service', 'Consulting, planning, and professional services', 5),
  ('Artisan Workshop', 'शिल्पी कार्यशाला', 'artisan_workshop', 'Craft studios and artisan producers', 6),
  ('Transportation', 'परिवहन', 'transportation', 'Transportation and logistics services', 7),
  ('Retail Shop', 'खुद्रा दोकान', 'retail_shop', 'Retail stores and shopping services', 8)
ON CONFLICT (slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_ne = EXCLUDED.name_ne,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order;
