#!/bin/bash

# Script to generate a comprehensive markdown analysis report
# Usage: ./generate_report.sh [directory_path] [output_file]

BASE_DIR="${1:-$(pwd)}"
OUTPUT_FILE="${2:-markdown_analysis_report.md}"

# Check if directory exists
if [ ! -d "$BASE_DIR" ]; then
    echo "Error: Directory '$BASE_DIR' does not exist."
    exit 1
fi

echo "Generating markdown analysis report..."
echo "Base directory: $BASE_DIR"
echo "Output file: $OUTPUT_FILE"
echo ""

# Create the report header
cat > "$OUTPUT_FILE" << 'EOF'
# Markdown Files Analysis Report

Generated on: $(date)
Project: Nepal Digital Tourism Infrastructure Documentation

## Summary

EOF

# Get basic statistics
total_files=$(find "$BASE_DIR" -name "*.md" -not -path "*/node_modules/*" -not -path "*/.git/*" | wc -l | tr -d ' ')
echo "Total markdown files: $total_files" >> "$OUTPUT_FILE"

# Add file distribution by month
echo "" >> "$OUTPUT_FILE"
echo "## File Distribution by Month" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
find "$BASE_DIR" -name "*.md" \
    -not -path "*/node_modules/*" \
    -not -path "*/.git/*" \
    -exec stat -f "%Sm" -t "%Y-%m" {} \; | \
    sort | uniq -c | sort -r | while read count month; do
    echo "- **$month**: $count files" >> "$OUTPUT_FILE"
done

# Add detailed file list
echo "" >> "$OUTPUT_FILE"
echo "## Files Sorted by Last Modified Date" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "| Date | Filename | Directory |" >> "$OUTPUT_FILE"
echo "|------|----------|-----------|" >> "$OUTPUT_FILE"

find "$BASE_DIR" -name "*.md" \
    -not -path "*/node_modules/*" \
    -not -path "*/.git/*" \
    -exec stat -f "%Sm|%N" -t "%Y-%m-%d %H:%M:%S" {} \; | \
    sort -r | \
    while IFS='|' read -r date file; do
        relative_path=$(echo "$file" | sed "s|$BASE_DIR/||")
        filename=$(basename "$file")
        dirname=$(dirname "$relative_path")
        
        # Escape pipes in markdown
        dirname=$(echo "$dirname" | sed 's/|/\\|/g')
        filename=$(echo "$filename" | sed 's/|/\\|/g')
        
        echo "| $date | $filename | $dirname |" >> "$OUTPUT_FILE"
    done

# Add recent activity section
echo "" >> "$OUTPUT_FILE"
echo "## Recent Activity (Last 7 Days)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

seven_days_ago=$(date -v-7d +%Y-%m-%d)
find "$BASE_DIR" -name "*.md" \
    -not -path "*/node_modules/*" \
    -not -path "*/.git/*" \
    -newermt "$seven_days_ago" \
    -exec stat -f "%Sm|%N" -t "%Y-%m-%d %H:%M:%S" {} \; | \
    sort -r | \
    while IFS='|' read -r date file; do
        relative_path=$(echo "$file" | sed "s|$BASE_DIR/||")
        echo "- **$date**: $relative_path" >> "$OUTPUT_FILE"
    done

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "*Report generated by markdown analysis script*" >> "$OUTPUT_FILE"

echo "Report generated successfully: $OUTPUT_FILE"
echo "Total files analyzed: $total_files"
